CREATE DATABASE mydatabase;
use mydatabase;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from my_table
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from my_table
where discount_applied = 'yes' and purchase_amount >=
(
select AVG(purchase_amount)
from my_table)

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, Round(AVG(review_rating),2) as 'Average product rating'
from my_table
group by item_purchased
order by AVG(review_rating) desc
limit 5


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select avg(purchase_amount) , shipping_type
from my_table
where shipping_type in ('standard','express')
group by shipping_type


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

select subscription_status,
count(customer_id) as 'total customer',
avg(purchase_amount) as 'average revenue',
sum(purchase_amount) as 'total revenue'
from my_table
group by subscription_status
order by 'total revenue','average revenue' desc


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM my_table
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as
(
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 AND 10 then 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
from my_table
)

select customer_segment ,count(*) as 'Number of customers'
from customer_type
group by customer_segment


-- Q8. What are the top 3 most purchased products within each category? 

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM my_table
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as "repeat buyers"
from my_table
where previous_purchases > 5
group by subscription_status-- 


-- Q10. What is the revenue contribution of each age group? 
select age_group, SUM(purchase_amount) as total_revenue
from my_table
group by age_group
order by total_revenue desc





